#############################################################################
# Makefile for building: lab2_1.app/Contents/MacOS/lab2_1
# Generated by qmake (3.1) (Qt 6.7.3)
# Project:  ../../lab2_1.pro
# Template: app
# Command: /Users/katyaaleinik/Qt/6.7.3/macos/bin/qmake -o Makefile ../../lab2_1.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I../../../lab2_code -I. -I/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers -I/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers -I/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/macx-clang -F/Users/katyaaleinik/Qt/6.7.3/macos/lib
QMAKE         = /Users/katyaaleinik/Qt/6.7.3/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/katyaaleinik/Qt/6.7.3/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/katyaaleinik/Qt/6.7.3/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = lab2_11.0.0
DISTDIR = /Users/katyaaleinik/Desktop/lab\ 2/lab2_code/build/Desktop_arm_darwin_generic_mach_o_64bit-Debug/.tmp/lab2_11.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/katyaaleinik/Qt/6.7.3/macos/lib
LIBS          = $(SUBLIBS) -F/Users/katyaaleinik/Qt/6.7.3/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../../main.cpp \
		../../widget.cpp moc_widget.cpp
OBJECTS       = main.o \
		widget.o \
		moc_widget.o
DIST          = /Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/spec_pre.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/device_config.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/unix.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/mac.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/macx.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/sanitize.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/gcc-base.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/clang.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/clang-mac.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/qconfig.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_charts.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qt_functions.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qt_config.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/macx-clang/qmake.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/spec_post.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/exclusive_builds.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/sdk.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/toolchain.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/toolchain.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/default_pre.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/default_pre.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/resolve_config.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/default_post.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/default_post.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/objective_c.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qml_debug.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/mac.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/warn_on.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/permissions.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qt.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/resources_functions.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/resources.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/moc.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/unix/opengl.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/uic.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/unix/thread.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qmake_use.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/file_copies.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/rez.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/testcase_targets.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/exceptions.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/yacc.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/lex.prf \
		../../../../lab2_1.pro ../../widget.h ../../main.cpp \
		../../widget.cpp
QMAKE_TARGET  = lab2_1
DESTDIR       = 
TARGET        = lab2_1.app/Contents/MacOS/lab2_1

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/katyaaleinik/Desktop/lab 2/lab2_code/lab2_1.pro


include /Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

lab2_1.app/Contents/MacOS/lab2_1: ui_widget.h $(OBJECTS)  
	@test -d lab2_1.app/Contents/MacOS/ || mkdir -p lab2_1.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../../lab2_1.pro /Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/macx-clang/qmake.conf /Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/spec_pre.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/device_config.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/unix.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/mac.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/macx.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/sanitize.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/gcc-base.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/clang.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/clang-mac.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/qconfig.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_charts.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qt_functions.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qt_config.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/macx-clang/qmake.conf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/spec_post.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/exclusive_builds.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/sdk.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/toolchain.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/toolchain.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/default_pre.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/default_pre.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/resolve_config.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/default_post.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/default_post.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/objective_c.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qml_debug.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/mac.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/warn_on.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/permissions.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qt.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/resources_functions.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/resources.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/moc.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/unix/opengl.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/uic.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/unix/thread.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qmake_use.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/file_copies.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/rez.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/testcase_targets.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/exceptions.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/yacc.prf \
		/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/lex.prf \
		../../lab2_1.pro \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../../lab2_1.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/spec_pre.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/device_config.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/unix.conf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/mac.conf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/macx.conf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/sanitize.conf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/gcc-base.conf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/gcc-base-mac.conf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/clang.conf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/common/clang-mac.conf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/qconfig.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_ext_freetype.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_ext_libjpeg.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_ext_libpng.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_charts.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_charts_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_chartsqml.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_core.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_core_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_designer_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_freetype_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_gui_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_help.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_help_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_linguist.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimedia.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_network.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_network_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_png_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qml_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlbuiltins_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3d.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quick_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_sql_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svg_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_tools_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_lib_xml_private.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qt_functions.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qt_config.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/macx-clang/qmake.conf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/spec_post.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/exclusive_builds.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/sdk.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/toolchain.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/toolchain.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/default_pre.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/default_pre.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/resolve_config.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/default_post.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/default_post.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/objective_c.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qml_debug.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/mac.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/warn_on.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/permissions.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qt.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/resources_functions.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/resources.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/moc.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/unix/opengl.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/uic.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/unix/thread.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/qmake_use.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/file_copies.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/rez.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/mac/asset_catalogs.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/testcase_targets.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/exceptions.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/yacc.prf:
/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/features/lex.prf:
../../lab2_1.pro:
/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Resources/QtGui.prl:
/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../../lab2_1.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

lab2_1.app/Contents/PkgInfo: 
	@test -d lab2_1.app/Contents || mkdir -p lab2_1.app/Contents
	@$(DEL_FILE) lab2_1.app/Contents/PkgInfo
	@echo "APPL????" > lab2_1.app/Contents/PkgInfo
lab2_1.app/Contents/Info.plist: 
	@test -d lab2_1.app/Contents || mkdir -p lab2_1.app/Contents
	@$(DEL_FILE) lab2_1.app/Contents/Info.plist
	@plutil -convert xml1 -o - /Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,3eQIJM.lab2-1,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},3eQIJM.lab2-1,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,lab2_1,g" -e "s,@LIBRARY@,lab2_1,g" -e "s,\$${EXECUTABLE_NAME},lab2_1,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >lab2_1.app/Contents/Info.plist

all: Makefile \
		lab2_1.app/Contents/PkgInfo \
		lab2_1.app/Contents/Info.plist lab2_1.app/Contents/MacOS/lab2_1

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../widget.h $(DISTDIR)/
	$(COPY_FILE) --parents ../../main.cpp ../../widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../../widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r lab2_1.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: ../../widget.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/QDir \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/qdir.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/QFileSystemModel \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/qfilesystemmodel.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/QModelIndex \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QListView \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qlistview.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/QImageWriter \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/qimagewriter.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QTableWidget \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QFileDialog \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QHeaderView \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qheaderview.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/libexec/moc
	/Users/katyaaleinik/Qt/6.7.3/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=16 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/katyaaleinik/Qt/6.7.3/macos/mkspecs/macx-clang -I'/Users/katyaaleinik/Desktop/lab 2/lab2_code' -I/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers -I/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers -I/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/16/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/katyaaleinik/Qt/6.7.3/macos/lib ../../widget.h -o moc_widget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: ../../widget.ui \
		/Users/katyaaleinik/Qt/6.7.3/macos/libexec/uic
	/Users/katyaaleinik/Qt/6.7.3/macos/libexec/uic ../../widget.ui -o ui_widget.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../../main.cpp ../../widget.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/QDir \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/qdir.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/QFileSystemModel \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/qfilesystemmodel.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/QModelIndex \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QListView \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qlistview.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/QImageWriter \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/qimagewriter.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QTableWidget \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QFileDialog \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QHeaderView \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qheaderview.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QApplication \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../../main.cpp

widget.o: ../../widget.cpp ../../widget.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/QDir \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/qdir.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/QFileSystemModel \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/qfilesystemmodel.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/QModelIndex \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QListView \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qlistview.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/QImageWriter \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtGui.framework/Headers/qimagewriter.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QTableWidget \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QFileDialog \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qfiledialog.h \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/QHeaderView \
		/Users/katyaaleinik/Qt/6.7.3/macos/lib/QtWidgets.framework/Headers/qheaderview.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o ../../widget.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/lab2_1/bin || mkdir -p $(INSTALL_ROOT)/opt/lab2_1/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lab2_1/bin/lab2_1.app
	
	$(QINSTALL) lab2_1.app $(INSTALL_ROOT)/opt/lab2_1/bin/lab2_1.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/lab2_1/bin/lab2_1.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/lab2_1/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

